language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_install:
  - gem install sass
before_script:
- npm install -g grunt-cli
- npm install -g bower
- grunt gh-pages-clean
- bower update
env:
  global:
  - DOCBASE_TOKEN=""
sudo: false
